(function(){
"use strict";
var key="hlp.notes",editing=-1;
function load(){try{var x=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(x)?x:[]}catch(e){return []}}
function save(x){try{localStorage.setItem(key,JSON.stringify(x));return true}catch(e){showTip("浏览器没有允许保存这条笔记");return false}}
function values(){var f=document.querySelector("#notes-form"),q=[];f.querySelectorAll("[name=question]").forEach(function(x){if(x.value.trim())q.push(x.value.trim())});return{where:f.where.value.trim(),since:f.since.value.trim(),severity:f.severity.value,previous:f.previous.value.trim(),checks:f.checks.value.trim(),department:f.department.value.trim(),requirements:f.requirements.value.trim(),questions:q,date:new Date().toLocaleDateString("zh-CN")}}
function renderList(){var list=document.querySelector("#note-list");if(!list)return;var notes=load();list.innerHTML="";if(!notes.length){list.innerHTML='<p class="card">还没有保存过笔记。</p>';return}notes.forEach(function(n,i){var d=document.createElement("div");d.className="note-item";d.innerHTML="<strong>"+escapeHtml(n.date||"未写日期")+"</strong><p>"+escapeHtml(n.where||"没有写哪里不舒服")+"</p><div class='button-row'><button class='btn secondary' data-edit='"+i+"'>继续修改</button><button class='btn gray' data-delete='"+i+"'>删除</button></div>";list.appendChild(d)})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function fillCard(n){var p=window.HLPProfile?HLPProfile.load():{};var severity={mild:"Mild",uncomfortable:"Uncomfortable",affects:"Affects eating and sleeping",severe:"Severe",unbearable:"Unbearable"}[n.severity]||"";var cn=["哪里不舒服："+(n.where||"未填写"),"从什么时候开始："+(n.since||"未填写"),"难受程度："+(document.querySelector("[name=severity] option:checked")||{}).textContent,"之前看过或吃过药："+(n.previous||"未填写"),"想检查："+(n.checks||"未填写"),"想挂科室："+(n.department||"未填写"),"对医院的要求："+(n.requirements||"未填写"),"要问医生："+(n.questions.join("；")||"未填写")];var en=["I don't speak English well. Please read this.","My name is "+(p.fullName||"")+". Date of birth: "+(p.birthYear||"")+".","I have had this problem for: "+(n.since||""),"Where it hurts: "+(n.where||""),"Severity: "+severity,"I would like to be checked for: "+(n.checks||""),"My long-term conditions: "+(p.conditionsEn||p.conditions||""),"I am allergic to: "+(p.allergiesEn||p.allergies||""),"I am currently taking: "+(p.medicationsEn||p.medications||""),"My questions: "+(n.questions.join("; ")||"")];document.querySelector("#visit-cn").innerHTML="<li>"+cn.map(escapeHtml).join("</li><li>")+"</li>";document.querySelector("#visit-en").innerHTML="<li>"+en.map(escapeHtml).join("</li><li>")+"</li>";document.querySelector("#visit-speak").setAttribute("data-speak",en.join(" "));document.querySelector("#visit-card").hidden=false;document.querySelector("#visit-card").scrollIntoView({behavior:"smooth"})}
var form=document.querySelector("#notes-form");if(!form)return;
document.querySelector("[data-add-question]").addEventListener("click",function(){var row=document.createElement("div");row.className="form-row";row.innerHTML='<label>再问医生一个问题</label><input name="question" type="text">';document.querySelector("#questions").appendChild(row);row.querySelector("input").focus()});
form.addEventListener("submit",function(e){e.preventDefault();var all=load(),n=values();if(editing>=0)all[editing]=n;else all.push(n);if(save(all)){editing=-1;renderList();showTip("笔记已经保存")}})
document.querySelector("[data-generate-card]").addEventListener("click",function(){fillCard(values())});
document.querySelector("#note-list").addEventListener("click",function(e){var eb=e.target.closest("[data-edit]"),db=e.target.closest("[data-delete]"),all=load();if(eb){editing=Number(eb.dataset.edit);var n=all[editing];["where","since","severity","previous","checks","department","requirements"].forEach(function(k){form.elements[k].value=n[k]||""});var qs=form.querySelectorAll("[name=question]");qs.forEach(function(x,i){x.value=(n.questions||[])[i]||""});form.scrollIntoView({behavior:"smooth"})}if(db&&confirm("确定删除这条笔记吗？")){all.splice(Number(db.dataset.delete),1);save(all);renderList()}});
document.querySelector("[data-fullscreen-card]").addEventListener("click",function(){document.querySelector("#visit-card").classList.toggle("card-overlay")});
renderList();
})();
